AUT="MuLiN Creator"
ENVVARS=envvars
HOOK_SUB_PROCESSES=false
IMPLICITAUTSTART=0
LANGUAGE=Python
OBJECTMAPSTYLE=script
TEST_CASES=tst_project1_build_case tst_project2_build_case tst_project3_case
VERSION=3
WRAPPERS=Qt
